### ISSUE TITLE
Remove pycache from repo and add to .gitignore

### ISSUE THREAD

**Issue by proan** [grt192/Swerve-UI-2025#1]
Python's cache folder (`__pyache__`) stores pre-compiled binaries and should be kept out of source control repositories because they are automatically generated from the code when it runs. Please also add the appropriate settings to a `.gitignore` file so that these files stay out of your git repos.

**Comment by Tonyxwu** [comment]
fixed

**Comment by proan** [comment]
Great, but you need to create a .gitignore file that makes git ignore the pycache folder or you'll keep adding them back in the future.

**Comment by proan** [comment]
Also, get in the habit of pushing to a feature branch and then opening a pull request to `main`. This way you can have a code review before breaking your main branch.

**Comment by Tonyxwu** [comment]
ok
